### ISSUE TITLE
Cannot get Jekyll to work on windows

### ISSUE THREAD

**Issue by ericadamski** [anthonyaubrey/anthonyaubrey.ca#1]
@thomasjbradley @anthonyaubrey is having a hard time installing jekyll on his windows machine, have you seen this before by any chance?

![jekyll error](https://cloud.githubusercontent.com/assets/6516758/19491353/a1f1cf3e-9540-11e6-88c3-56f8daf77c30.png)

**Comment by anthonyaubrey** [comment]
Hey! 

A relative helped me out with this. It turned out to be a specific folder in the ruby structure. rubygems. After removing it and reinstalling it through the command prompt i was able to install jekyll.
